recommendations/catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='catalog'),
    path('types/<slug:type_slug>/', views.TypeView.as_view(), name='types'),
    path('types/<slug:type_slug>/level1/<slug:level1_slug>/', views.Level1View.as_view(), name='level1'),
    path('types/<slug:type_slug>/level1/<slug:level1_slug>/level2/<slug:level2_slug>/',
         views.Level2View.as_view(), name='level2'),
    path('types/<slug:type_slug>/level1/<slug:level1_slug>/level2/<slug:level2_slug>/level3/<slug:level3_slug>/',
         views.Level3View.as_view(), name='level3'),
    path('search/<str:search_string>', views.SearchView.as_view(), name='search'),
    path('signup2group/<str:group>/', views.SignUp2GroupView.as_view(), name='signup2group'),
    path('group_success_signup/<int:pk>/<str:date_choice>/', views.SuccessSignup.as_view(), name='group_success_signup'),
]

recommendations/recommendations/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static

from recommendations import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='default')),
    path('test/', include('rec_app.urls')),
    path('catalog/', include('catalog.urls')),
    re_path('chaining/', include('smart_selects.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recommendations/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('index/', views.IndexView.as_view(), name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

recommendations/catalog/models.py
from django.db import models
from django.db.models import Count

from services.utils import unique_slugify
from users.models import Profile


class ActivityTypes(models.Model):
    activity_type = models.CharField(max_length=255, unique=True, verbose_name='Тип активности')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')
    objects = models.Manager()

    def __str__(self):
        return f'{self.activity_type}'

    def save(self, *args, **kwargs):
        """
        Сохранение полей модели при отсутствии заполнения
        """
        if not self.slug:
            self.slug = unique_slugify(self, self.activity_type)
        super().save(*args, **kwargs)


class ActivityLevel1(models.Model):
    activity_type = models.ForeignKey(ActivityTypes, on_delete=models.CASCADE)
    id_level = models.IntegerField()
    level = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')
    objects = models.Manager()

    def __str__(self):
        return f'{self.level}'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, self.level)
        super().save(*args, **kwargs)


class ActivityLevel2(models.Model):
    activity_type = models.ForeignKey(ActivityLevel1, on_delete=models.CASCADE)
    id_level = models.IntegerField()
    level = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')
    objects = models.Manager()

    def __str__(self):
        return f'{self.level}'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, self.level)
        super().save(*args, **kwargs)


class ActivityLevel3(models.Model):
    activity_type = models.ForeignKey(ActivityLevel2, on_delete=models.CASCADE)
    id_level = models.IntegerField()
    level = models.CharField(max_length=255)
    descript_level = models.TextField(null=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')
    objects = models.Manager()

    def __str__(self):
        return f'{self.level}:\n{self.descript_level}'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, self.level)
        super().save(*args, **kwargs)


class Groups(models.Model):
    uniq_id = models.IntegerField()
    level = models.ForeignKey(ActivityLevel3, on_delete=models.CASCADE)
    objects = models.Manager()

    def __str__(self):
        return f'{self.uniq_id}'


class GroupsCorrect(models.Model):
    group_id = models.ForeignKey(Groups, on_delete=models.CASCADE)
    level = models.ForeignKey(ActivityLevel3, on_delete=models.CASCADE)
    address = models.TextField()
    admin_district = models.CharField(max_length=255)
    start_date = models.CharField(max_length=32, null=True)
    end_date = models.CharField(max_length=32, null=True)
    weekday = models.CharField(max_length=32, null=True)
    start_time = models.CharField(max_length=32, null=True)
    end_time = models.CharField(max_length=32, null=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')
    objects = models.Manager()

    class Meta:
        ordering = ('-group_id',)

    def __str__(self):
        return f'{self.group_id}'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, self.group_id)
        super().save(*args, **kwargs)

    @staticmethod
    def get_user_groups(user):
        user_groups = Attends.objects.select_related('group_id').filter(user_id=user.pk).distinct()
        return user_groups


class Attends(models.Model):
    uniq_id = models.IntegerField(null=True)
    group_id = models.ForeignKey(Groups, on_delete=models.CASCADE)
    user_id = models.ForeignKey(Profile, on_delete=models.CASCADE)
    online = models.BooleanField()
    date_attend = models.DateField()
    start_time = models.CharField(max_length=32)
    end_time = models.CharField(max_length=32)
    objects = models.Manager()

    def __str__(self):
        return f'{self.uniq_id}'

    @staticmethod
    def get_top_level3(activity_type: ActivityTypes):
        """Function for get top level3 in attends, priority - offline"""
        top_off = Attends.objects.exclude(online='1') \
                      .values('group_id__level') \
                      .annotate(count_level3=Count('group_id__level')) \
                      .order_by('-count_level3')[:10]
        top_offline = ActivityLevel3.objects.filter(
            pk__in=[i.get('group_id__level') for i in top_off])
        level3_offline = top_offline.filter(activity_type__activity_type__activity_type=activity_type)

        top_on = Attends.objects.filter(online='1') \
                     .values('group_id__level') \
                     .annotate(count_level3=Count('group_id__level')) \
                     .order_by('-count_level3')[:5]
        top_online = ActivityLevel3.objects.filter(
            pk__in=[i.get('group_id__level') for i in top_on])
        level3_online = top_online.filter(activity_type__activity_type__activity_type=activity_type)

        # если нет level3 по этому типу активности в топе
        if not level3_online.exists() and not level3_offline.exists():
            return top_offline, top_online
        return level3_offline, level3_online

recommendations/catalog/forms.py
from django import forms
from bootstrap_datepicker_plus.widgets import DatePickerInput
import datetime as dt

from catalog.models import Attends, Groups
from services.dictionaries import WEEKDAYS_DICT
from users.models import Profile


class SearchForm(forms.Form):
    search_activity = forms.CharField(max_length=255)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.label = ""


class DateTimeChoiceForm(forms.Form):
    def __init__(self, *args, group, user, **kwargs):
        super().__init__(*args, **kwargs)
        self.group = group
        self.user = user
        self.fields['date_choice'] = forms.DateField(
            label='Выберите подходящую дату:',
            required=True,
            widget=DatePickerInput(
                options={
                    'format': 'DD.MM.YYYY',
                    'minDate': dt.datetime.strptime(
                        self.group.start_date, '%d.%m.%Y'),
                    'maxDate': dt.datetime.strptime(
                        self.group.end_date, '%d.%m.%Y') + dt.timedelta(days=1),
                }
            )
        )

    def clean(self):
        data = self.cleaned_data
        date_choice = data.get('date_choice')
        if date_choice:
            weekday_choice = date_choice.weekday()
            weekday = int(WEEKDAYS_DICT[self.group.weekday])
            if weekday_choice != weekday:
                raise forms.ValidationError('День недели должен совпадать с выбранным.')
        return data

    def save(self):
        attend = Attends(
            group_id=Groups.objects.get(pk=self.group.group_id.pk),
            user_id=Profile.objects.get(pk=self.user.pk),
            online=True if 'ОНЛАЙН' in self.group.level.level else False,
            date_attend=self.cleaned_data['date_choice'],
            start_time=self.group.start_time,
            end_time=self.group.end_time,
        )
        attend.save()

recommendations/catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, FormView
from django_filters.views import FilterView
from django.contrib import messages

from catalog.filters import GroupsFilterSearch, GroupsFilterCatalog
from catalog.forms import SearchForm, DateTimeChoiceForm
from catalog.models import ActivityTypes, ActivityLevel1, ActivityLevel2, ActivityLevel3, Attends, \
    GroupsCorrect
from django.core.exceptions import ObjectDoesNotExist


class IndexView(FormView):
    template_name = 'catalog/catalog.html'
    extra_context = {
        'message': 'Каталог занятий',
        'searcher': 'Введите слово для поиска по каталогу'
    }
    form_class = SearchForm
    context_object_name = 'activity_types'

    def get_success_url(self, search_activity=None):
        return reverse_lazy('catalog:search', args=(search_activity,))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['activity_types'] = ActivityTypes.objects.all().order_by('id')
        return context

    def form_valid(self, form):
        search_activity = form.cleaned_data.get('search_activity')
        return redirect(self.get_success_url(search_activity))


class SearchView(FilterView):
    model = GroupsCorrect
    paginate_by = 10
    template_name = 'catalog/search_results.html'
    extra_context = {'message': 'Результаты поиска',
                     'message_error': 'Мы ничего не нашли по вашему запросу'}
    context_object_name = 'groups_list'
    filterset_class = GroupsFilterSearch

    def get_queryset(self):
        search_string = self.kwargs.get('search_string')
        level3 = ActivityLevel3.objects.filter(Q(descript_level__icontains=search_string) |
                                               Q(level__icontains=search_string))
        groups_list = GroupsCorrect.objects.filter(level__in=level3).exclude(start_date='')
        return groups_list


class TypeView(ListView):
    model = ActivityLevel1
    template_name = 'catalog/catalog_levels_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message'] = 'Выберите раздел по вкусу:'
        context['next_page'] = 'level1/'
        return context

    def get_queryset(self):
        type_slug = self.kwargs.get('type_slug')
        activity_type = get_object_or_404(ActivityTypes, slug=type_slug)
        level1 = ActivityLevel1.objects.filter(activity_type=activity_type).order_by('id')
        return level1


class Level1View(ListView):
    model = ActivityLevel2
    template_name = 'catalog/catalog_levels_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message'] = 'Выберите раздел по настроению:'
        context['next_page'] = 'level2/'
        return context

    def get_queryset(self):
        level1_slug = self.kwargs.get('level1_slug')
        level1 = get_object_or_404(ActivityLevel1, slug=level1_slug)
        level2 = ActivityLevel2.objects.filter(activity_type=level1)
        return level2


class Level2View(ListView):
    model = ActivityLevel3
    template_name = 'catalog/catalog_levels_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message'] = 'Выберите раздел по любви:'
        context['next_page'] = 'level3/'
        return context

    def get_queryset(self):
        level2_slug = self.kwargs.get('level2_slug')
        level2 = get_object_or_404(ActivityLevel2, slug=level2_slug)
        level3 = ActivityLevel3.objects.filter(activity_type=level2)
        return level3


class Level3View(FilterView):
    model = GroupsCorrect
    paginate_by = 10
    template_name = 'catalog/groups.html'
    context_object_name = 'groups_list'
    extra_context = {'message': 'Выберите удобную для Вас группу',
                     'message_error': 'Мы ничего не нашли по вашему запросу'}
    filterset_class = GroupsFilterCatalog
    level3_slug: int

    def get_slug(self):
        if not hasattr(self, 'level3_slug'):
            self.level3_slug = self.kwargs.get('level3_slug')
        return self.level3_slug

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['level3'] = get_object_or_404(ActivityLevel3, slug=self.get_slug())
        return context

    def get_queryset(self):
        level3 = get_object_or_404(ActivityLevel3, slug=self.get_slug())
        groups_list = GroupsCorrect.objects.filter(level=level3).exclude(start_date='')
        return groups_list


class HttpResponseRedirect:
    pass


class SignUp2GroupView(LoginRequiredMixin, FormView):
    template_name = 'catalog/signup2group.html'
    extra_context = {'message': 'Выберите дату посещения'}
    form_class = DateTimeChoiceForm
    context_object_name = 'group'
    redirect_field_name = 'users:index'
    group: GroupsCorrect

    def get_group(self):
        if not hasattr(self, 'group'):
            self.group = get_object_or_404(GroupsCorrect, pk=self.kwargs['group'])
        return self.group

    def get_success_url(self, date_choice=None):
        return reverse_lazy('catalog:group_success_signup', args=(self.get_group().pk, date_choice))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['group'] = self.get_group()
        return context

    def form_valid(self, form):
        date_choice = form.cleaned_data.get('date_choice')
        try:
            attend = Attends.objects.get(
                user_id=self.request.user.pk,
                date_attend=date_choice,
                start_time=self.group.start_time
            )
            messages.error(self.request, 'Вы уже записаны на эту дату и время')
            return redirect(self.request.META.get('HTTP_REFERER'))
        except ObjectDoesNotExist:
            form.save()
            return redirect(self.get_success_url(date_choice))

    def get_form_kwargs(self):
        kwargs = super(SignUp2GroupView, self).get_form_kwargs()
        kwargs['group'] = self.get_group()
        kwargs['user'] = self.request.user
        return kwargs


class SuccessSignup(LoginRequiredMixin, DetailView):
    model = GroupsCorrect
    context_object_name = 'group'
    template_name = 'catalog/group_success_signup.html'
    extra_context = {'message': 'Вы успешно записались!'}
    redirect_field_name = reverse_lazy('users:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['date_choice'] = self.kwargs['date_choice']
        return context

    def get_object(self, queryset=None):
        return get_object_or_404(GroupsCorrect, pk=self.kwargs['pk'])

recommendations/catalog/templates/catalog/catalog.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<div class="container-fluid">
    <div class="row my-5">
        <h1 class="text-center">{{ message }} </h1>
    </div>
    <div class="col-md-4">
        <h3> {{ searcher }}</h3>
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-success btn-block btn-lg">Искать</button>
        </form>
    </div>
</div>
<div class="col-md-12 col-md-push-3">
    <div class="row">
        {% for activity_type in activity_types %}
        <div class="col-sm-4 text-center">
            <a class="btn btn-success btn-block btn-lg"
               href="types/{{ activity_type.slug }}" role="button"
               style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: 2.75rem;">
                {{ activity_type.activity_type }}
            </a>
        </div>
        {% endfor %}
    </div>
</div>
<div class="col-md-12 col-md-push-3">
    <div class="row">
        <div class="col-sm-4">
            <div class="panel">
                <img src="/static/catalog/images/chess_play.jpg"
                     class="img-fluid img-thumbnail border border-success">
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel">
                <img src="/static/catalog/images/play.jpg" class="img-fluid img-thumbnail border border-success">
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel">
                <img src="/static/catalog/images/snow.jpg" class="img-fluid img-thumbnail border border-success">
            </div>
        </div>
    </div>
</div>
{% endblock %}

recommendations/catalog/templates/catalog/catalog_levels_page.html
{% extends 'base.html' %}
<h1> Каталог</h1>
{% block content %}
<div class="container-fluid">
    <h1>{{message}} </h1>
</div>
<div class="container-fluid">
    <div class="row my-5">
        <div class="col-md-12">
            <ul class="list-group">
                {% for level in object_list %}
                <li class="list-group-item list-group-item-dark">
                    <a class="btn btn-success btn-block btn-lg" role="button"
                       href="{{next_page}}{{ level.slug }}"
                       style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: 1.75rem;">
                        {{ level.level }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

recommendations/catalog/templates/catalog/group_details.html
<div class="container">
    <h2 class="text-center">{{group.level.level}}</h2>
    <h4 class="text-center">{{group.level.descript_level}}</h4>
    <h4 class="text-center"><b>Номер группы: </b>{{group.group_id.uniq_id}}</h4>
    {% if 'ОНЛАЙН' in group.level.level %}
    <h3 class="text_center">Занятия проходят он-лайн.</h3>
    {% else %}
    <h3 class="text-center"><b>Адрес:</b> {{ group.address }}</h3>
    {% endif %}
</div>

recommendations/catalog/templates/catalog/group_success_signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row my-5">
        <h1 class="text-center">{{ message }}!</h1>
    </div>
    <div class="row my-3">
        <div class="col-md-6">
            {% include './group_details.html' %}
            <div class="container">
                <h3 class="text-center"><b>Дата: </b>{{ date_choice }}</h3>
                <h3 class="text-center"><b>Время: </b>{{group.start_time }} - {{ group.end_time }}</h3>
            </div>
        </div>
        <div class="col-md-6">
            <img src="{% static 'images/success.png' %}" class="mx-auto d-block" width="500px">
        </div>
    </div>
</div>
{% endblock %}

recommendations/catalog/templates/catalog/groups.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<div class="container-fluid">
    {% if groups_list %}
    <div class="row my-5">
        <div class="col-md-6">
            <h2>{{level3.level}}</h2>
            <br/>
            <h3>{{level3.descript_level}}</h3>
        </div>
    </div>
    <div class="row my-3">
        <h4>{{message}}:</h4>
        {% include 'groups_list.html' %}
        {% include 'filter_with_onoff.html' %}
        {% else %}
    </div>
    <div class="col-md-12">
        {% include 'ups.html' %}
    </div>
</div>
{% endif %}
{% include 'pagination.html' %}
{% endblock %}

recommendations/catalog/templates/catalog/level3.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load widget_tweaks %}
{% block content %}
<div class="container-fluid">
    {% if groups %}
    <div class="row my-5">
        <div class="col-md-6">
            <h2>{{level3.level}}</h2>
            <br/>
            <h3>{{level3.descript_level}}</h3>
        </div>
        <div class="col-md-2">
        </div>
        <div class="col-md-4">
            {% if not 'ОНЛАЙН' in level3.level %}
            <h4>Введите адрес или район для поиска:</h4>
            <form method="GET" action="">
                {% csrf_token %}
                <div style="display: grid">
                    {% for field in groups_filter.form %}
                    <div id="form-field-{{ forloop.counter0 }}">
                        {{ field.label_tag }}
                        {% render_field field class="form-control" %}
                    </div>
                    {% endfor %}
                </div>
                <button type="submit" class="btn btn-success mb-3 mt-2">Выбрать
                </button>
            </form>
            {% endif %}
        </div>
    </div>
    <div class="row my-3">
        <div class="col-md-9">
            <h4>Выберите удобную для Вас группу:</h4>
            <ul class="list-group">
                {% for group in groups %}
                {% if 'ОНЛАЙН' in group.level.level %}
                <li class="list-group-item list-group-item-dark" style="font-size: 25px">
                    <p><b>Номер группы:</b> {{group.uniq_id}}.</p>
                    <p><b>Расписание:</b> {{group.schedule_active}}</p>
                    <p>Занятия проходят он-лайн.</p>
                    {% if user.is_authenticated %}
                    <a class="btn btn-success btn-block btn-lg"
                       href=" {% url 'catalog:signup2group' group.id %}" role="button"
                       style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: 1.75rem;">Записаться</a>
                    {% else %}
                    <p>Для записи необходимо войти в систему.</p>
                    {% endif %}
                </li>
                {% else %}
                <li class="list-group-item list-group-item-dark" style="font-size: 25px">
                    <p><b>Номер группы:</b> {{group.uniq_id}}.</p>
                    <p><b>Адрес:</b> {{ group.address }}</p>
                    <p><b>Расписание:</b> {{group.schedule_active}}</p>
                    {% if user.is_authenticated %}
                    <a class="btn btn-success btn-block btn-lg"
                       href=" {% url 'catalog:signup2group' group.id %}" role="button"
                       style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: 1.75rem;">Записаться</a>
                    {% else %}
                    <p>Для записи необходимо войти в систему.</p>
                    {% endif %}
                </li>
                {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
    {% else %}
    <div class="col-md-12">
        <img src="/static/images/ups.png" class="mx-auto d-block" width="400px">
        <h3>Мы ничего не нашли по вашему запросу.<br/>Попробуйте еще. </h3>
    </div>
    {% endif %}
</div>
<div class="container">
    {% if groups %}
    {% include "pagination.html" with page=groups %}
    {% endif %}
</div>
{% endblock %}

recommendations/catalog/templates/catalog/search_results.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<div class="container-fluid">
    {% if groups_list %}
    <div class="row my-5">
        <div class="col-md-6">
            <h1>{{ message }}</h1>
        </div>
    </div>
    <div class="row my-5">
        {% include 'groups_list.html' %}
        {% include 'filter_with_onoff.html' %}
    </div>
    {% else %}
    <div class="col-md-12">
        {% include 'ups.html' %}
    </div>
    {% endif %}
</div>
{% include 'pagination.html' %}
{% endblock %}

recommendations/catalog/templates/catalog/signup2group.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
<div class="container-fluid">
    <div class="row my-5">
        <h1 class="text-center">{{ message }}:</h1>
        <div class="col-md-6">
            {% include './group_details.html' %}
            <div class="container">
                <h5 class="text_center"><b>Расписание: </b>с {{ group.start_date }} до {{ group.end_date}}</h5>
                <h5 class="text-center"><b>день недели: </b>{{ group.weekday }}, время {{ group.start_time }} - {{group.end_time}}</h5>
            </div>
            <div class="container">
                <form action="" method="post">
                    {{ form.media }}
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button type="submit" class="btn btn-success btn-block btn-lg">Записаться</button>
                </form>
            </div>
        </div>
        <div class="col-md-6">
            <img src="{% static 'images/choice_2.png' %}" class="mx-auto d-block" width="500px">
        </div>
    </div>
</div>
{% endblock %}

recommendations/catalog/templates/catalog/singup_group_details.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row my-5">
        <h1 class="text-center">Выберите время и дату посещения:</h1>
    </div>
</div>
<div class="col-md-12">
    <h5 class="text-center">{{message}}</h5>
    {% if 'ОНЛАЙН' in group.level %}
        <h5>{{group.level}}</h5>
        <p><b>Номер группы: </b> {{group.uniq_id}}.</p>
        <p>Занятия проходят он-лайн.</p>
        <p><b>Расписание:</b> {{group.schedule_active}}</p>
    {% else %}
        <h5>{{group.level}}</h5>
        <p><b>Номер группы: </b>{{group.uniq_id}}.</p>
        <p><b>Адрес:</b> {{ group.address }}</p>
        <p><b>Расписание:</b> {{group.schedule_active}}</p>
    {% endif %}
    <img src="/static/images/success.png" class="mx-auto d-block" width="400px">
</div>
{% endblock %}

recommendations/catalog/templates/catalog/types.html
{% extends 'base.html' %}
<h1> Каталог</h1>
{% block content %}
<div class="container-fluid">
    <h1>Выберите раздел по настроению: </h1>
</div>
<div class="container-fluid">
    <div class="row my-5">
        <div class="col-md-12">
            <ul class="list-group">
                {% for level in level1 %}
                <li class="list-group-item list-group-item-dark">
                    <a class="btn btn-success btn-block btn-lg" role="button"
                       href="level1/{{ level.slug }}"
                       style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: 1.75rem;">
                        {{ level.level }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}